CREATE TABLE members(
   member_id INT GENERATED BY DEFAULT AS IDENTITY
             PRIMARY KEY,
   first_name VARCHAR(100) NOT NULL,
   last_name VARCHAR(100) NOT NULL,
   gender CHAR(1)
);

INSERT INTO
   members(first_name,last_name,gender)
VALUES
   ('Mary','Jane','F'),
   ('Peter','Crane','M');
