CREATE TABLE daily_routines(
   routine_id INT
      GENERATED BY DEFAULT AS IDENTITY
      NOT NULL PRIMARY KEY,
   routine VARCHAR(100) NOT NULL,
   start_at TIME NOT NULL
);

INSERT INTO
   daily_routines(routine, start_at)
VALUES
   ('Get up','06:00'),
   ('Brush your teeth','06:05'),
   ('Have Breakfast','06:15'),
   ('Go to School','06:45'),
   ('Go home','17:00');
